### ISSUE TITLE
 sns左にずらす

### ISSUE THREAD

**Issue by shinnoske0727** [shinnoske0727/nakajiman#20]

**Comment by shinnoske0727** [comment]
やった
![image](https://user-images.githubusercontent.com/6258669/52911122-f0797480-32e2-11e9-9405-3786ae32e74e.png)
![image](https://user-images.githubusercontent.com/6258669/52911124-f8d1af80-32e2-11e9-833c-16f1cc167a82.png)

**Comment by nakaj1man** [comment]
確認したのでクローズします。
