### ISSUE TITLE
[SP]Titleのサイズがおかしい

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#28]
![image](https://user-images.githubusercontent.com/20411997/52643463-6adf7880-2f20-11e9-87a8-ad4718d0cc92.png)
![image](https://user-images.githubusercontent.com/20411997/52643468-72068680-2f20-11e9-9a15-bec69c381b08.png)

**Comment by shinnoske0727** [comment]
直した

**Comment by nakaj1man** [comment]
修正確認したのでクローズ
