### ISSUE TITLE
[SP]トップのカテゴリボタンタップ時に画面遷移せず、ホバーアニメーションが動き出す

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#30]
![image](https://user-images.githubusercontent.com/20411997/52643630-c90c5b80-2f20-11e9-8232-caffadf8531d.png)

**Comment by shinnoske0727** [comment]
治った

**Comment by nakaj1man** [comment]
修正確認したのでクローズ
