### ISSUE TITLE
[SP]WORKSのカテゴリータブのアンダーバーのサイズが適切じゃない

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#32]
【正】
![image](https://user-images.githubusercontent.com/20411997/52643935-4df77500-2f21-11e9-8f04-707957aa9b0a.png)

【誤】
![image](https://user-images.githubusercontent.com/20411997/52643972-5f408180-2f21-11e9-907a-3b8eec861e60.png)

**Comment by shinnoske0727** [comment]
直した。

**Comment by nakaj1man** [comment]
修正確認したのでクローズします
