### ISSUE TITLE
[SP]トップのレイアウトが仕様書通りじゃない

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#33]
ロゴの差し替えと一緒に対応お願いします

【正】
![top iphone xs](https://user-images.githubusercontent.com/20411997/52645134-826c3080-2f23-11e9-8858-229d5c83875f.png)

【誤】
![img_1386](https://user-images.githubusercontent.com/20411997/52645168-92841000-2f23-11e9-9ef9-8074e94c2211.PNG)

**Comment by shinnoske0727** [comment]
やった

**Comment by nakaj1man** [comment]
確認したのでクローズします
