### ISSUE TITLE
[SP]矢印ボタンの位置が仕様と異なる

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#48]
![img_1434](https://user-images.githubusercontent.com/20411997/53084909-21f17a80-3545-11e9-9b06-79f70d668d96.PNG)

正しくはBottomから `24px`
https://zpl.io/am9wg5Q

**Comment by shinnoske0727** [comment]
やった

**Comment by nakaj1man** [comment]
確認したのでクローズ
