### ISSUE TITLE
[SP]SPでスクロール時headerのベースカラーが表示されない

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#51]
![img_1434 2](https://user-images.githubusercontent.com/20411997/53296035-d98ad300-384a-11e9-8fe4-833cc66534d6.PNG)

正しくは `H:64px` のHeaderが存在する
https://zpl.io/awWPkAK

**Comment by shinnoske0727** [comment]
やった

**Comment by nakaj1man** [comment]
確認したのでクローズ
