### ISSUE TITLE
[PC][SP]TOPのカテゴリーボタンのテキストサイズが仕様と異なる

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#58]
![image](https://user-images.githubusercontent.com/20411997/53495277-f3464780-3ae2-11e9-8a15-7f88c19641f8.png)

**Comment by nakaj1man** [comment]
![image](https://user-images.githubusercontent.com/20411997/53495250-e7f31c00-3ae2-11e9-972b-89d947fc5889.png)

**Comment by shinnoske0727** [comment]
直した

**Comment by nakaj1man** [comment]
確認したのでクローズ
