### ISSUE TITLE
[PC][SP]WORKSのタブのマージンサイズが仕様と異なる

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#59]
[PC]
![image](https://user-images.githubusercontent.com/20411997/53496225-e9bddf00-3ae4-11e9-97b8-8259cda09a08.png)

[SP]
![image](https://user-images.githubusercontent.com/20411997/53495734-de1de880-3ae3-11e9-8c72-0d61576b9bdf.png)

**Comment by shinnoske0727** [comment]
zeplinで話した感じに並べた

**Comment by nakaj1man** [comment]
@shinnoske0727 
テキスト間のマージンサイズはいい感じ！
ですが別の問題が発生したので下記確認してください。


[PC]
めっちゃ細かいけどheaderのサイズが1px短くなった。
![image](https://user-images.githubusercontent.com/20411997/53685558-ad49e780-3d5f-11e9-9608-7c39d50a44b3.png)

[SP]
headerのサイズがアンダーバーの2px分短くなってしまい、スクロールするとアンダーバーがheader内に収まらなくなった。
![image](https://user-images.githubusercontent.com/20411997/53685591-1df10400-3d60-11e9-9ff1-ad22c3c9845f.png)
![image](https://user-images.githubusercontent.com/20411997/53685595-2fd2a700-3d60-11e9-8ae2-153592f23671.png)
![image](https://user-images.githubusercontent.com/20411997/53685614-5abcfb00-3d60-11e9-9d70-c99cd0dab4e7.png)

**Comment by shinnoske0727** [comment]
PCはzeplinと照らし合わせてるけどあってる気がする

**Comment by nakaj1man** [comment]
SP大丈夫でした
PCの方まだ直ってなかったのでアサイン戻します
![image](https://user-images.githubusercontent.com/20411997/53704602-693f0b80-3e61-11e9-9569-cbcc75655788.png)

**Comment by nakaj1man** [comment]
確認したのでクローズ
