### ISSUE TITLE
[PC]ABOUTの左右のマージンサイズが仕様と異なる

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#60]
![image](https://user-images.githubusercontent.com/20411997/53496458-6bae0800-3ae5-11e9-8d31-a00946ea9567.png)

**Comment by nakaj1man** [comment]
上下のマージンのズレは直接話して仕様を変更したため。

**Comment by shinnoske0727** [comment]
やった

**Comment by nakaj1man** [comment]
確認したのでクローズ
