### ISSUE TITLE
[PC][直接相談]黒ボタンホバー時のアウトラインのサイズ調整

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#61]
ちょっと太すぎるので直接話して修正
![image](https://user-images.githubusercontent.com/20411997/53496629-c6476400-3ae5-11e9-8cda-aec550dcb83f.png)

**Comment by shinnoske0727** [comment]
直した

**Comment by nakaj1man** [comment]
確認したのでクローズ
