### ISSUE TITLE
[SP]ABOUTのマージンサイズが仕様と異なる

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#62]
説明文に関しては行間が違うっぽい。
![image](https://user-images.githubusercontent.com/20411997/53497248-1ffc5e00-3ae7-11e9-9aa8-bd4e3507c134.png)

**Comment by shinnoske0727** [comment]
line-height を1.83にした

**Comment by nakaj1man** [comment]
確認したのでクローズ
