### ISSUE TITLE
[PC]WORKSのカテゴリータブのアンダーバーのサイズが仕様と異なる

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#63]
![image](https://user-images.githubusercontent.com/20411997/53497798-5686a880-3ae8-11e9-854e-aaad5fc89544.png)

**Comment by shinnoske0727** [comment]
下の棒がそれぞれ48pxのマージンがあるのでそれに合わせた。

**Comment by nakaj1man** [comment]
確認したのでクローズ
