### ISSUE TITLE
[SP]WORKS作品切り替えボタンにOpacityがかかっていない

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#65]
正しくは不透明度80%がボタン全体にかかっている
![image](https://user-images.githubusercontent.com/20411997/53498333-78345f80-3ae9-11e9-8f9b-7d2eeafc83fb.png)

**Comment by shinnoske0727** [comment]
かけた

**Comment by nakaj1man** [comment]
確認したのでクローズ
