### ISSUE TITLE
[PC][SP][直接相談]矢印ボタンの白い矢印の位置が仕様と異なる

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#67]
[正]
![image](https://user-images.githubusercontent.com/20411997/53499086-03622500-3aeb-11e9-9d9a-7a60b329b160.png)

[誤]
![image](https://user-images.githubusercontent.com/20411997/53499051-f04f5500-3aea-11e9-9941-99f4227f09f9.png)

**Comment by shinnoske0727** [comment]
直した

**Comment by nakaj1man** [comment]
確認したのでクローズ
