### ISSUE TITLE
[SP]TOPのマージンサイズを調整

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#68]
### 調整箇所
- サムネイルとロゴ間のマージン
- ロゴとボタン間のマージン
- ボタンとfooter間のマージン

詳しくは下記リンクを参照
https://zpl.io/2pnP6X8

**Comment by shinnoske0727** [comment]
直した

**Comment by nakaj1man** [comment]
確認したのでクローズ
