### ISSUE TITLE
[SP]TOPのヘッダーに背景が敷かれてない

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#73]
![s__37814330](https://user-images.githubusercontent.com/20411997/53679362-34bb3a80-3d0f-11e9-95fc-c767357a6041.jpg)

**Comment by shinnoske0727** [comment]
敷いた

**Comment by nakaj1man** [comment]
iphone8が手元にないので実機で確認次第クローズします

**Comment by nakaj1man** [comment]
修正されてなかったのでアサイン戻します。
![image](https://user-images.githubusercontent.com/20411997/53690345-03447c80-3dac-11e9-81fc-5d5bcfa59b89.png)

下記リンク先のデザインのようにiPhone8などのHeightの短い端末ではスクロール時にHeaderが表示されて欲しいです。
https://zpl.io/a3eRY1N

**Comment by shinnoske0727** [comment]
ごめん。レイヤーの位置がKVよりも奥になっちまってた。修正しました

**Comment by nakaj1man** [comment]
まだ直ってなかったのでアサイン戻します

**Comment by nakaj1man** [comment]
確認したのでクローズ
