### ISSUE TITLE
[PC][SP]WORKS詳細ページのマージンサイズが仕様と異なる

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#77]
[PC]
- タイトルとdescriptionのマージンズレ
<img width="1398" alt="2019-03-02 20 18 36" src="https://user-images.githubusercontent.com/20411997/53683268-1ae71b00-3d42-11e9-866d-bfd235b83c54.png">
- descriptionと作品画像のマージンズレ
<img width="1396" alt="2019-03-02 20 18 51" src="https://user-images.githubusercontent.com/20411997/53683269-1cb0de80-3d42-11e9-90ba-da5e015f057b.png">

[SP]
- タイトルとdescriptionのマージンズレ
<img width="377" alt="2019-03-02 23 20 24" src="https://user-images.githubusercontent.com/20411997/53683282-3520f900-3d42-11e9-896d-217963a3340c.png">
- descriptionと作品画像のマージンズレ
<img width="380" alt="2019-03-02 23 21 22" src="https://user-images.githubusercontent.com/20411997/53683284-3d793400-3d42-11e9-9211-60b9bae24616.png">

**Comment by shinnoske0727** [comment]
ひとまずzeplinの数字には合わせました

**Comment by nakaj1man** [comment]
zeplin or sketchの問題でlineheightのズレがどうしても起きてキリがないのでこれでFIX
