### ISSUE TITLE
[PC]TOPのサムネ画像切り替わり時に同じ作品が重複することがあった

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#78]
<img width="1440" alt="2019-03-02 23 58 45 2" src="https://user-images.githubusercontent.com/20411997/53683700-43bddf00-3d47-11e9-98b9-7e1c83e410ca.png">

**Comment by shinnoske0727** [comment]
ロジック修正した

**Comment by nakaj1man** [comment]
問題なさそうなのでクローズ
