### ISSUE TITLE
[PC]Headerのサイズがおかしくなった

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#79]
前回は問題なかった新たに発生したissue
![image](https://user-images.githubusercontent.com/20411997/53683414-e07e7d80-3d43-11e9-97fc-0329e1e15cc7.png)
<img width="1048" alt="2019-03-02 23 38 20" src="https://user-images.githubusercontent.com/20411997/53683472-5b479880-3d44-11e9-97f6-0e5b8f118447.png">

**Comment by shinnoske0727** [comment]
直した

**Comment by nakaj1man** [comment]
確認したのでクローズ
