### ISSUE TITLE
作品抜け漏れ

### ISSUE THREAD

**Issue by nakaj1man** [shinnoske0727/nakajiman#81]
東武線アプリ4枚目
https://drive.google.com/file/d/1LhXvDNac7vl6pvn_T9aA9xjKms_hbQ2H/view?usp=sharing

イラスト
https://drive.google.com/drive/u/0/folders/18e7qBLxqlX1SgCi2M2vOcCQE2Gu3XUYj

**Comment by shinnoske0727** [comment]
追加した

**Comment by nakaj1man** [comment]
確認したのでクローズ
